# Generated by Django 4.0.6 on 2022-07-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oj", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="code_file",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
