# Generated by Django 4.0.6 on 2022-07-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_user_solution_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='Code',
        ),
    ]
